language: java
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.m2
install: true
script:
-  mvn clean install -Pprod

# since tests are already executed during build
# so no need to run it again.
after_success:
- mvn jacoco:report coveralls:report
